export const GENRE_CHANGE = 'GENRE_CHANGE';
export const GENRE_INIT = 'GENRE_INIT';
export const GENRE_RESET = 'GENRE_RESET';

export const MUTCH_EXCEL_CHANGE = 'MUTCH_EXCEL_CHANGE';
export const MUTCH_RESET = 'MUTCH_RESET';

export const POPUP_OPEN = 'POPUP_OPEN';
export const POPUP_CLOSE = 'POPUP_CLOSE';

export const SPINNER_MUTCH_HIDE = 'SPINNER_MUTCH_HIDE';
export const SPINNER_MUTCH_SHOW = 'SPINNER_MUTCH_SHOW';
export const SPINNER_GENRE_HIDE = 'SPINNER_GENRE_HIDE';
export const SPINNER_GENRE_SHOW = 'SPINNER_GENRE_SHOW';

export const QUESTION_ANSWER = 'QUESTION_ANSWER';
