export const GENRE_CHANGE = 'GENRE_CHANGE';
export const GENRE_INIT = 'GENRE_INIT';

export const MUTCH_EXCEL_CHANGE = 'MUTCH_EXCEL_CHANGE';
export const MUTCH_RESTART = 'MUTCH_RESTART';

export const POPUP_OPEN = 'POPUP_OPEN';
export const POPUP_CLOSE = 'POPUP_CLOSE';

export const QUESTION_ANSWER = 'QUESTION_ANSWER';
